apiVersion: v1
kind: ConfigMap
metadata:
  name: korvet-config
data:
  # Redis connection - Docker Redis Enterprise on host
  KORVET_REDIS_URI: "redis://host.docker.internal:12000"

  # Metrics
  KORVET_REDIS_METRICS_ENABLED: "true"
  KORVET_REDIS_METRICS_HISTOGRAM: "true"
