# Secret for Korvet Flink Cold Storage Writer
# Contains sensitive credentials - DO NOT commit real values to source control
apiVersion: v1
kind: Secret
metadata:
  name: korvet-flink-secret
  labels:
    app: korvet-flink
    component: cold-storage-writer
type: Opaque
stringData:
  # AWS credentials for S3 access (only needed for static credentials)
  # For EKS with IRSA, omit these and use IAM roles instead
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_SECRET_KEY"
  
  # Redis password (if authentication is enabled)
  # REDIS_PASSWORD: "REPLACE_WITH_REDIS_PASSWORD"

